[package]
name = "wcloud"
version = "0.1.0"
authors = ["afrmtbl <afrmtbl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.1"
ab_glyph = "0.2.5"
image = "0.23.10"
rand = "0.7.3"
